export const USER = {
  UID: "UID",
  UNAME: "UNAME",
  UTYPE: "UTYPE",
  AUTH_STATE: "AUTH_STATE",
  PROFILE_IMG: "PROFILE_IMG",
  POINT: "POINT",
  POST_CNT: "POST_CNT",
  IS_AUTH: "IS_AUTH",
  IS_ADMIN: "IS_ADMIN",
  PROFILE_CHANGE: {
    FORM_DATA: "PROFILE_CHANGE_FORM_DATA",
    UNAME: "PROFILE_CHANGE_UNAME"
  }
};
export const RANK = {
  TOP: ["RANK_TOP_1", "RANK_TOP_2", "RANK_TOP_3"]
};
export const NOTICE = {
  STATE: "NOTICE_STATE",
  TITLE: "NOTICE_TITLE",
  BODY: "NOTICE_BODY",
  BUTTON: "NOTICE_BUTTON",
  STYLE: {
    HEIGHT: "NOTICE_STYLE_HEIGHT",
    DISPLAY: "NOTICE_STYLE_DISPLAY"
  }
};
export const POST = {
  PRE: {
    CATEGORY: "POST_PRE_CATEGORY",
    TITLE: "POST_PRE_TITLE",
    CONTENT: "POST_PRE_CONTENT"
  },
  UPLOAD: "POST_UPLOAD"
};
