export const USER = {
  UID: "UID",
  UNAME: "UNAME",
  UTYPE: "UTYPE",
  AUTH_STATE: "AUTH_STATE",
  PROFILE_IMG: "PROFILE_IMG",
  POINT: "POINT",
  POST_CNT: "POST_CNT",
  IS_AUTH: "IS_AUTH",
  IS_ADMIN: "IS_ADMIN"
};
